name: C/C++ Qt CI

on:
  push:
    tags:
      - "v*.*.*"
  
jobs:
  deploy-win64:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:win64
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - name: Compile project for Windows
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv release/src.exe /qt-sudoku-logic-solver-${{github.ref_name}}.exe
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        name: Qt Sudoku Logic Solver ${{github.ref_name}}
        body_path: ./.github/CHANGELOG.md
        files: /qt-sudoku-logic-solver-${{github.ref_name}}.exe
      
  deploy-linux:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:linux
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - name: Compile project for Linux
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv src /qt-sudoku-logic-solver-${{github.ref_name}}
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        name: Qt Sudoku Logic Solver ${{github.ref_name}}
        body_path: ./.github/CHANGELOG.md
        files: /qt-sudoku-logic-solver-${{github.ref_name}}
