name: C/C++ Qt CI

on:
  push:
    branches: [ "test_workflows" ]
  pull_request:
    branches: [ "test_workflows" ]
  
jobs:
  deploy-win64:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:win64
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv release/src.exe /qt-sudoku-logic-solver-${{github.ref_name}}.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /qt-sudoku-logic-solver-${{github.ref_name}}.exe
      
  deploy-linux:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:linux
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv src /qt-sudoku-logic-solver-${{github.ref_name}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /qt-sudoku-logic-solver-${{github.ref_name}}
