name: C/C++ Qt CI

on:
  push:
    branches: [ "test_workflows" ]
  pull_request:
    branches: [ "test_workflows" ]

env:
  RELEASE_VERSION: ${GITHUB_REF#refs/*/}
  
jobs:


  deploy-win64:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:win64
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Print release version
      run: echo $RELEASE_VERSION
    - name: compile
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv release/src.exe release/qt-sudoku-logic-solver.exe
    - uses: actions/upload-artifact@v3
      with:
        name: qt-logic-solver-Windows
        path: /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src/release/src.exe
      
  deploy-linux:
    runs-on: ubuntu-20.04
    container:
      image: alonkop/qtlogicsolver:linux
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: |
       echo "Compiling project..."
       cd /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src
       qmake
       make -j$(nproc)
       mv src qt-sudoku-logic-solver
    - uses: actions/upload-artifact@v3
      with:
        name: qt-logic-solver-Linux
        path: /__w/qt-sudoku-logic-solver/qt-sudoku-logic-solver/src/src